export const genres = [
   {
      id: "IWZ9Z08B",
      name: "Nhạc Trữ Tình",
      title: "Nhạc Trữ Tình",
      alias: "nhac-tru-tinh",
      link: "/genre/IWZ9Z08B",
   },
   {
      id: "IWZ97FCD",
      name: "V-Pop",
      title: "V-Pop",
      alias: "v-pop",
      link: "/genre/IWZ97FCD",
   },
   {
      id: "IWZ9Z08O",
      name: "US-UK",
      title: "US-UK",
      alias: "us-uk",
      link: "/genre/IWZ9Z08O",
   },
   {
      id: "IWZ9Z09A",
      name: "Electronic / Dance",
      title: "Electronic / Dance",
      alias: "electronic-dance",
      link: "/genre/IWZ9Z09A.html",
   },
   {
      id: "IWZ9Z08W",
      name: "K-pop",
      title: "K-pop",
      alias: "k-pop",
      link: "/genre/IWZ9Z08W.html",
   },
   {
      id: "IWZ9Z09O",
      name: "Dance Pop",
      title: "Dance Pop",
      alias: "dance-pop",
      link: "/genre/IWZ9Z09O.html",
   },
   {
      id: "IWZ9Z089",
      name: "Rap Việt",
      title: "Rap Việt",
      alias: "rap-viet",
      link: "/genre/IWZ9Z089.html",
   },
   {
      id: "IWZ9Z09B",
      name: "Rap / Hip Hop",
      title: "Rap / Hip Hop",
      alias: "rap-hip-hop",
      link: "/genre/IWZ9Z09B.html",
   },
   {
      id: "IWZ9Z09D",
      name: "R&B / Soul",
      title: "R&B / Soul",
      alias: "r-b-soul",
      link: "/genre/IWZ9Z09D.html",
   },
   {
      id: "IWZ9Z0BA",
      name: "OST",
      title: "OST",
      alias: "ost",
      link: "/genre/IWZ9Z0BA",
   },
   {
      id: "29246926",
      name: "Lofi",
      title: "Lofi",
      alias: "lofi",
      link: "/genre/29246926",
   },
   {
      id: "27492479",
      name: "Acoustic",
      title: "Acoustic",
      alias: "acoustic",
      link: "/genre/27492479",
   },
   {
      id: "24898698",
      name: "Indie",
      title: "Indie",
      alias: "Indie",
      link: "/genre/24898698",
   },
];
